# Generated by Django 5.2.7 on 2026-01-20 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='studysession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.module'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.submodule'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'created_at'], name='core_studys_user_id_6b40bc_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['subject', 'created_at'], name='core_studys_subject_4c2bbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ended_at_gte_started_at_or_null'),
        ),
    ]
